if (WIN32)
    add_compile_definitions(PLATFORM_WINDOWS)
elseif (APPLE)
    add_compile_definitions(PLATFORM_APPLE)
elseif (UNIX AND NOT APPLE)
    add_compile_definitions(PLATFORM_LINUX)
else()
    message(FATAL_ERROR "Unsupported platform")
endif()

if(CMAKE_SIZEOF_VOID_P EQUAL 8)
    add_compile_definitions(PLATFORM_64_BIT)
else()
    add_compile_definitions(PLATFORM_32_BIT)
endif()

if (CMAKE_BUILD_TYPE STREQUAL "Debug")
    message(STATUS "Building debug version")
    add_compile_definitions(SWARM_BUILD_DEBUG)
else()
    add_compile_definitions(SWARM_BUILD_RELEASE)
endif()
